

spring:
  datasource:
    password: 1234
    url: jdbc:mysql://localhost:3306/springdb
    username: springUser
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true